export const CSvgIcons = [
  {name: 'users', path: 'assets/images/icons/users-icon.svg'},
  {name: 'chat', path: 'assets/images/icons/chat-icon.svg'},
  {name: 'logout', path: 'assets/images/icons/logout-icon.svg'},
  {name: 'phone', path: 'assets/images/icons/phone-icon.svg'},
  {name: 'questionInCircle', path: 'assets/images/icons/question-in-circle.svg'},
  {name: 'settings', path: 'assets/images/icons/settings-icon.svg'},
  {name: 'dots', path: 'assets/images/icons/dots.svg'},
  {name: 'search', path: 'assets/images/icons/search-icon.svg'},
  {name: 'plus', path: 'assets/images/icons/plus-icon.svg'},
  {name: 'not-read', path: 'assets/images/icons/not-read-icon.svg'},
  {name: 'read-mess', path: 'assets/images/icons/read-icon.svg'},
  {name: 'close', path: 'assets/images/icons/close.svg'},
  {name: 'file', path: 'assets/images/icons/file-icon.svg'},
  {name: 'block', path: 'assets/images/icons/block-icon.svg'},
]
